<a href="https://colab.research.google.com/github/iqlore-collab/A-B-Testing-Chi-Squer/blob/main/GITHUB_chi_square_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency

##TASK:

We have tested 4 versions A, B, C and D of the "SHOP NOW" button on Client's website.

After the experiment is complete with 1500 visits each, these are the results:

- Version A: 134 clicks, 1500 visits.
- Version B: 102 clicks, 1500 visits.
- Version C: 78 clicks, 1500 visits.
- Version D: 129 clicks, 1500 visits.

##Solution:

Following steps:
1. State the Null and the Alternative Hypotheses.
2. Define your alpha.
3. Collect data that is random and independent
4. Calculate the test result
5. Interpret the test result

### 1.&nbsp; Stating the Null and the Alternative Hypotheses.

Null Hypothesis: The click rate for all the versions are equal/There is no difference in the conversion rates (clicks) between the four button versions.

Alternative Hypothesis: At least one of the versions have a better or worse click rate than the others/at least one of the button versions has a statistically different conversion rate than the others.

### 2.&nbsp;Defining our alpha.

Common values are 0.1, 0.05 and 0.01. We go with the least restrictive one and pick 0.1.

In [ ]:
alpha = 0.1

### 3.&nbsp; Collecting data that is random and independent

In [ ]:
Click_sn = [134, 102, 78, 129]
No_click_sn = [1500-134, 1500-102, 1500-78, 1500-129]

observed_results_sn = pd.DataFrame(
    [Click_sn, No_click_sn], columns=["A", "B", "C", "D"], index=["Click_sn", "No-click_sn"]
)
observed_results_sn

                A     B     C     D
Click_sn      134   102    78   129
No-click_sn  1366  1398  1422  1371

In [ ]:
# setting up no_clocks using list comprehension --> shorthand version of writing a for-loop
No_click = [1500 - x for x in Click_sn]
No_click

[1366, 1398, 1422, 1371]

In [ ]:
# us the numpy array -> no column and row labels
observed = np.array([
    [134, 102, 78, 129],          # clicks
    [1500-134, 1500-102, 1500-78, 1500-129]   # no-clicks
])
observed

### 4.&nbsp; Calculate the test result.

In [ ]:
chisq, pvalue, df, expected = chi2_contingency(observed_results_sn)

In [ ]:
chisq

np.float64(19.720109791770167)

In [ ]:
pvalue

np.float64(0.00019398896739266587)

In [ ]:
df

3

In [ ]:
expected

array([[ 110.75,  110.75,  110.75,  110.75],
       [1389.25, 1389.25, 1389.25, 1389.25]])

### 5.&nbsp; Interpret the test result.

In [ ]:
if pvalue < alpha:
  print("""The p-value is smaller than alpha.
  We reject the null hypothesis. There is a sufficient evidence to suggest/say
  at least one of the websites has a significantyl different click through rate
  compared to the others. Identify the better performing website with post-hoc test.""")
else:
  print("""We do not reject the null hypothesis. No sufficient evidence to suggest
  at least one of the websites has a significantyl different click through rate
  compared to the others.""")

The p-value is smaller than alpha.
  We reject the null hypothesis. There is a sufficient evidence to suggest/say
  at least one of the websites has a significantyl different click through rate
  compared to the others. Identify the better performing website with post-hoc test.

In [ ]:
# loot at each website's CTR (click trough rate)
ctr_a = observed_results_sn.loc["Click_sn", "A"] / sum(observed_results_sn["A"])
ctr_b = observed_results_sn.loc["Click_sn", "B"] / sum(observed_results_sn["B"])
ctr_c = observed_results_sn.loc["Click_sn", "C"] / sum(observed_results_sn["C"])
ctr_d = observed_results_sn.loc["Click_sn", "D"] / sum(observed_results_sn["D"])

# create a table with all four versions and their click-through rates.
ctrs = pd.DataFrame(
    {"version": ["A", "B", "C", "D"], "CTR": [ctr_a, ctr_b, ctr_c, ctr_d]}
)

ctrs.sort_values("CTR", ascending=False)

  version       CTR
0       A  0.089333
3       D  0.086000
1       B  0.068000
2       C  0.052000